//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.MODEL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ABS_LIFE_V2DbContext : DbContext
    {
        public ABS_LIFE_V2DbContext()
            : base("name=ABS_LIFE_V2DbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBIL_ANN_POLICY_BENEFRY> TBIL_ANN_POLICY_BENEFRY { get; set; }
        public virtual DbSet<TBIL_ANN_POLICY_DET> TBIL_ANN_POLICY_DET { get; set; }
        public virtual DbSet<TBIL_ANN_POLICY_PREM_INFO> TBIL_ANN_POLICY_PREM_INFO { get; set; }
        public virtual DbSet<tbil_CUST_detail> tbil_CUST_detail { get; set; }
        public virtual DbSet<tbil_ins_detail> tbil_ins_detail { get; set; }
    }
}
