//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.MODEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbil_CUST_detail
    {
        public string TBIL_CUST_ID { get; set; }
        public string TBIL_CUST_CODE { get; set; }
        public decimal TBIL_CUST_REC_ID { get; set; }
        public string TBIL_CUST_CATG { get; set; }
        public string TBIL_CUST_MDLE { get; set; }
        public string TBIL_CUST_DESC { get; set; }
        public string TBIL_CUST_SHRT_DESC { get; set; }
        public string TBIL_CUST_OCCUP_CODE { get; set; }
        public string TBIL_CUST_SOURCE_BIZ { get; set; }
        public string TBIL_CUST_BRANCH { get; set; }
        public string TBIL_CUST_ADRES1 { get; set; }
        public string TBIL_CUST_ADRES2 { get; set; }
        public string TBIL_CUST_PHONE1 { get; set; }
        public string TBIL_CUST_PHONE2 { get; set; }
        public string TBIL_CUST_EMAIL1 { get; set; }
        public string TBIL_CUST_EMAIL2 { get; set; }
        public string TBIL_CUST_STAFF_YN { get; set; }
        public string TBIL_CUST_TAG { get; set; }
        public string TBIL_CUST_FLAG { get; set; }
        public string TBIL_CUST_OPERID { get; set; }
        public Nullable<System.DateTime> TBIL_CUST_KEYDTE { get; set; }
        public string TBIL_CUST_OLD_NEW { get; set; }
    }
}
