//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.MODEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBIL_ANN_POLICY_BENEFRY
    {
        public decimal TBIL_ANN_BENF_REC_ID { get; set; }
        public string TBIL_ANN_BENF_FILE_NO { get; set; }
        public string TBIL_ANN_BENF_MDLE { get; set; }
        public string TBIL_ANN_BENF_PROP_NO { get; set; }
        public string TBIL_ANN_BENF_BENF_COVER_ID { get; set; }
        public string TBIL_ANN_BENF_POLY_NO { get; set; }
        public Nullable<decimal> TBIL_ANN_BENF_SNO { get; set; }
        public Nullable<decimal> TBIL_ANN_BENF_COVER_ID { get; set; }
        public string TBIL_ANN_BENF_TYPE { get; set; }
        public string TBIL_ANN_BENF_CAT { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_BENF_BDATE { get; set; }
        public string TBIL_ANN_BENF_AGE { get; set; }
        public string TBIL_ANN_BENF_RELATN_CD { get; set; }
        public string TBIL_ANN_BENF_NAME { get; set; }
        public Nullable<decimal> TBIL_ANN_BENF_PCENT { get; set; }
        public string TBIL_ANN_BENF_GURDN_NM { get; set; }
        public string TBIL_ANN_BENF_ADRESS { get; set; }
        public string TBIL_ANN_BENF_TAG { get; set; }
        public string TBIL_ANN_BENF_FLAG { get; set; }
        public string TBIL_ANN_BENF_OPERID { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_BENF_KEYDTE { get; set; }
        public string TBIL_ANN_BENF_OLD_NEW { get; set; }
    }
}
