//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.MODEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBIL_ANN_POLICY_PREM_INFO
    {
        public string TBIL_ANN_POL_PRM_FILE_NO { get; set; }
        public decimal TBIL_ANN_POL_PRM_REC_ID { get; set; }
        public string TBIL_ANN_POL_PRM_MDLE { get; set; }
        public string TBIL_ANN_POL_PRM_PROP_NO { get; set; }
        public string TBIL_ANN_POL_PRM_POLY_NO { get; set; }
        public string TBIL_ANN_POL_PRM_PRDCT_CD { get; set; }
        public string TBIL_ANN_POL_PRM_PLAN_CD { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_PERIOD_YRS { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POL_PRM_FROM { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POL_PRM_TO { get; set; }
        public string TBIL_ANN_POL_PRM_CURRCY { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PURCHASE_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PURCHASE_FC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PREM_WITH_LS_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PREM_WITH_LS_FC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PREM_WITHOUT_LS_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PREM_WITHOUT_LS_FC { get; set; }
        public Nullable<decimal> TBIL_ANN_ANNUAL_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_ANNUAL_FC { get; set; }
        public byte[] TBIL_ANN_MONTHLY_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_MONTHLY_FC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_ANN_CONTRIB_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_ANN_CONTRIB_FC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_MTH_CONTRIB_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_MTH_CONTRIB_FC { get; set; }
        public string TBIL_ANN_POL_PRM_LIFE_COVER { get; set; }
        public string TBIL_ANN_POL_SA_FROM_PRM { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_SA_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_SA_FC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_LIFE_COVER_SA_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_LIFE_COVER_SA_FC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_FREE_COV_LMT_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_FREE_COV_LMT_FC { get; set; }
        public string TBIL_ANN_POL_PRM_MODE_PAYT { get; set; }
        public string TBIL_ANN_POL_PRM_RT_TAB_FIX { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_RT_FIXED { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_RT_FIX_PER { get; set; }
        public string TBIL_ANN_POL_PRM_RATE_CD { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_RATE { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_RATE_PER { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_NO_INSTAL { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_MOP_RATE { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_EXCHG_RATE { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_DISCNT_PCENT { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_LOAD_PCENT { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_FREE_LIFECOVER_LMT_LC { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_FREE_LIFECOVER_LMT_FC { get; set; }
        public string TBIL_ANN_POL_PRM_RT_APPLIED_ON { get; set; }
        public string TBIL_ANN_POL_PRM_RT_BONUS_CD { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POL_ANNUITY_PAYT_START { get; set; }
        public string TBIL_ANN_POL_ANNUITY_MOP { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_GUARANTEE_PERIOD_YRS { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_ANNUAL_PCENT_PYMT_INCREASE { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_DEATH_BENEFIT_ANNUAL_FACTOR { get; set; }
        public string TBIL_ANN_POL_PRM_ALLOC_CD { get; set; }
        public string TBIL_ANN_POL_PRM_SCH_TERM { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_FEE_PRD { get; set; }
        public Nullable<decimal> TBIL_ANN_POL_PRM_ENROL_NO { get; set; }
        public string TBIL_ANN_POL_PRM_TAG { get; set; }
        public string TBIL_ANN_POL_PRM_FLAG { get; set; }
        public string TBIL_ANN_POL_PRM_OPERID { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POL_PRM_KEYDTE { get; set; }
    }
}
