//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.MODEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBIL_ANN_POLICY_DET
    {
        public decimal TBIL_ANN_POLY_REC_ID { get; set; }
        public string TBIL_ANN_POLY_FILE_NO { get; set; }
        public string TBIL_ANN_POLY_MDLE { get; set; }
        public string TBIL_ANN_POLY_PROPSAL_NO { get; set; }
        public string TBIL_ANN_POLY_POLICY_NO { get; set; }
        public string TBIL_ANN_POLY_PRDCT_CD { get; set; }
        public string TBIL_ANN_POLY_PLAN_CD { get; set; }
        public string TBIL_ANN_POLY_COVER_CD { get; set; }
        public string TBIL_ANN_POLY_UNDW_YR { get; set; }
        public string TBIL_ANN_POLY_BRANCH_CD { get; set; }
        public string TBIL_ANN_POLY_DEPT_CD { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_PRPSAL_ISSUE_DATE { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_PRPSAL_RECD_DT { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_PROPSL_ACCPT_DT { get; set; }
        public string TBIL_ANN_POLY_PROPSL_ACCPT_STATUS { get; set; }
        public Nullable<System.DateTime> TBIL_POLICY_ISSUE_DT { get; set; }
        public Nullable<System.DateTime> TBIL_POLICY_EFF_DT { get; set; }
        public string TBIL_ANN_POLY_CUST_CODE { get; set; }
        public string TBIL_ANN_POLY_SOURC_BIZ { get; set; }
        public string TBIL_ANN_POLY_AGCY_CODE { get; set; }
        public string TBIL_ANN_POLY_ASSRD_CD { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_ASSRD_BDATE { get; set; }
        public string TBIL_ANN_POLY_ASSRD_HEIGHT { get; set; }
        public string TBIL_ANN_POLY_ASSRD_WEIGHT { get; set; }
        public string TBIL_ANN_POLY_ASSRD_HEIGHT_TYP { get; set; }
        public string TBIL_ANN_POLY_ASSRD_WEIGHT_TYP { get; set; }
        public string TBIL_ANN_POLY_AGE_PROOF { get; set; }
        public string TBIL_ANN_POLY_ASSRD_AGE { get; set; }
        public string TBIL_ANN_POLY_ASSRD_NATIONLTY { get; set; }
        public string TBIL_ANN_POLY_GENDER { get; set; }
        public string TBIL_ANN_POLY_MARITAL { get; set; }
        public string TBIL_ANN_POLY_OCCUPATN { get; set; }
        public string TBIL_ANN_POLY_OCCUTN_CLASS { get; set; }
        public string TBIL_ANN_POLY_RELIGN_CD { get; set; }
        public string TBIL_ANN_POLY_ASSRD_RELATN { get; set; }
        public string TBIL_ANN_POLY_ASSRD_PLACE_BIRTH { get; set; }
        public string TBIL_ANN_POLY_STATUS { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_STATUS_DATE { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_WAIVER_DT { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_PAIDUP_DT { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_CANCEL_DT { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_LAPSE_DT { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_REACTIVATE_DT { get; set; }
        public string TBIL_ANN_POLY_LAST_EMPLOYER { get; set; }
        public string TBIL_ANN_POLY_LAST_EMPLOYER_ADRES { get; set; }
        public string TBIL_ANN_POLY_RETIREE_PFA { get; set; }
        public string TBIL_ANN_POLY_RETIREE_PIN_NO { get; set; }
        public string TBIL_ANN_POLY_RETIREE_OCCUP { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_RETIREMENT_DATE { get; set; }
        public string TBIL_ANN_POLY_ACCOUNT_NAME { get; set; }
        public string TBIL_ANN_POLY_ACCOUNT_NO { get; set; }
        public string TBIL_ANN_POLY_BANK_NAME { get; set; }
        public string TBIL_ANN_POLY_BANK_ADRES { get; set; }
        public string TBIL_ANN_POLY_BANK_SORT_CODE { get; set; }
        public string TBIL_ANN_POLY_TAG { get; set; }
        public string TBIL_ANN_POLY_FLAG { get; set; }
        public string TBIL_ANN_POLY_OPERID { get; set; }
        public Nullable<System.DateTime> TBIL_ANN_POLY_KEYDTE { get; set; }
        public string TBIL_ANN_POLY_REF_NEW { get; set; }
    }
}
