//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABS.MODEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbil_ins_detail
    {
        public string TBIL_INSRD_ID { get; set; }
        public string TBIL_INSRD_CODE { get; set; }
        public decimal TBIL_INSRD_REC_ID { get; set; }
        public string TBIL_INSRD_MDLE { get; set; }
        public string TBIL_INSRD_CLASS { get; set; }
        public string TBIL_INSRD_SURNAME { get; set; }
        public string TBIL_INSRD_FIRSTNAME { get; set; }
        public string TBIL_INSRD_ADRES1 { get; set; }
        public string TBIL_INSRD_ADRES2 { get; set; }
        public string TBIL_INSRD_PHONE1 { get; set; }
        public string TBIL_INSRD_PHONE2 { get; set; }
        public string TBIL_INSRD_EMAIL1 { get; set; }
        public string TBIL_INSRD_EMAIL2 { get; set; }
        public Nullable<decimal> TBIL_INSRD_CR_LIMIT { get; set; }
        public string TBIL_INSRD_OCCUP_CODE { get; set; }
        public string TBIL_INSRD_SOURCE_BIZ { get; set; }
        public string TBIL_INSRD_PAY_MODE { get; set; }
        public string TBIL_INSRD_BRNCH_CODE { get; set; }
        public string TBIL_INSRD_TAG { get; set; }
        public string TBIL_INSRD_FLAG { get; set; }
        public string TBIL_INSRD_OPERID { get; set; }
        public Nullable<System.DateTime> TBIL_INSRD_KEYDTE { get; set; }
        public string TBIL_INSRD_OLD_NEW { get; set; }
    }
}
